title: "Nora Yang"
name: "Nora Yang"
description: "Data Scientist (Machine Learning)"
url: "https://yynora.github.io"
baseurl: ""
repository: "yynora/yynora.github.io"
masthead_title: "Nora Yang"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

locale: "en-US"
timezone: "America/Los_Angeles"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

author:
  name   : "Nora Yang"
  avatar : "/assets/images/profile.png"
  bio    : "Data Scientist (Machine Learning)"
  location: "Atlanta, GA"
  email  : "norayang@gatech.edu"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://www.linkedin.com/in/yynora"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yynora"
    - label: "Resume"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/NoraYang_resume.pdf"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

atom_feed:
  hide: true

search: false
breadcrumbs: false
words_per_minute: 200
